apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
  labels:
    app: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: brv147/playground:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /config  
      volumes:
      - name: config-volume
        configMap:
          name: pet-config
          items:
          - key: profile.properties
            path: application.properties
          - key: mysql.properties
            path: application-mysql.properties
